#!/bin/bash
# bashrc-git control


RUNDIR="/run/user/$UID/bash-git-prompt"
INSTANCE_RUNDIR="/run/user/$UID/bash-git-prompt/instances/$BASH_GIT_PROMPT_PID"

THIS_SCRIPT=`realpath "${BASH_SOURCE[0]}"`
BGP_INSTALLDIR=`dirname "$THIS_SCRIPT"`
. "$BGP_INSTALLDIR/bash-git-prompt-functions.sh"


function bgp_disable(){
	touch $INSTANCE_RUNDIR/disabled
}

function bgp_enable(){
	rm -f $INSTANCE_RUNDIR/disabled
}

function bgp_clear_cache(){
	rm -rf $RUNDIR/cache/directories
	rm -rf $RUNDIR/cache/repositories
	cat <<HEREDOC
Cache cleared. 
If your current working directory is (part of) a Git repository on a slow
medium (e.g.  NFS share), then it might take some time for bash-git-prompt to
repopulate the cache for this repository.
HEREDOC
}

function bgp_refresh(){
	repo_root=`bgp_get_pwd_repository_root`
	if [ ! "$repo_root" = "" ]; then
		repo_root_hash=`bgp_hash "$repo_root"`
		repo_cache_file="$RUNDIR/cache/repositories/$repo_root_hash"
		if [ -w "$repo_cache_file" ]; then
			rm "$repo_cache_file" && echo "Cache for repository '$repo_root' cleared - bash prompt should refresh automatically" || exit 1
		else
			echo "No cache entry found for repository '$repo_root' (or cache not writable) - unable to refresh." >& 2
		fi
	else 
		echo "Can't find repository root - unable to refresh." >& 2
		exit 1
	fi
}

function usage(){
	echo "Usage: bash-git-prompt [command] [parameter(s)]"
	echo ""
	echo "Available commands:"
	echo "  disable:     temporarily disables bash-git-prompt"
	echo "  enable:      (re-)enables bash-git-prompt"
	echo "  clear-cache: force wipe of cached information about all Git repositories"
	echo "  refresh:     refreshes the information on the current repository"
}

if [ -z "$BASH_GIT_PROMPT_PID" ]; then
	echo "bash-git-prompt not installed or initialised. Please follow the installation instructions and edit ~/.bashrc accordingly." >& 2
	exit 1
fi

case "$1" in
disable)	bgp_disable
		;;
enable)		bgp_enable
		;;
clear-cache)	bgp_clear_cache
		;;
refresh)	bgp_refresh
		;;
*)	echo "Unknown or missing command-line parameter" >& 2
	usage
	;;
esac

